name: Build and Push Using Shared Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-push:
    if: github.event_name != 'pull_request'

    permissions:
      contents: read

    strategy:
      matrix:
        version:
          - '18.20.8'
          - '20.19.3'
          - '21.7.3'
          - '22.14.0'

    uses: nstwf-d/docker-ci/.github/workflows/docker-build-push.yaml@main
    secrets: inherit
    with:
      image_version: ${{ matrix.version }}
      dockerhub_image: nstwf/${{ github.event.repository.name }}
      ghcr_image: ghcr.io/${{ github.repository }}
      docker_extra_build_args: |
        NODE_VERSION=${{ matrix.version }}
